### ISSUE TITLE
Invoke-FalconRTt

### ISSUE THREAD

**Issue by antmar904** [CrowdStrike/psfalcon#150]
**Describe the bug**
When trying to run a RTR command against a number of computers (2 for testing) PowerShell ISE freezes with high resource utilization.

The array successfully returns the correct number count and format.

**To Reproduce**
Here is the PS script that I run:

$CSIds = @(Get-Content -Path C:\Temp\CS\CS1.txt)
Invoke-FalconRtr ls C:\ -HostIds $csids

Here is the contents of C:\Temp\CS\CS1.txt

0034f74058744742a0386ba7f8b4e7c9
2a080c622e07460486990f294f473253

**Expected behavior**
To return the directory listing of C:\ from all aid's from stdout.

**Environment (please complete the following information):**
 - OS: Windows 10 20H2
 - PowerShell: PSVersion 5.1.19041.1320
 - PSFalcon: 2.15

**Additional context**

**Comment by bk-cs** [comment]
Can you re-run this with `$VerbosePreference = 'Continue'` so I can tell where the problem might begin?

Also, try running the following steps in a standard PowerShell session:
```
$CSIds = @(Get-Content -Path C:\Temp\CS\CS1.txt)
Import-Module -Name PSFalcon
Request-FalconToken -ClientId <client_id> -ClientSecret <client_secret> -Cloud <cloud>
Invoke-FalconRtr ls C:\ -HostIds $CSIds
```

**Comment by bk-cs** [comment]
We did some live troubleshooting and this issue seems to be restricted to the installation of PowerShell that @antmar904 is using.

We installed PowerShell Core and everything worked normally. Ultimately we couldn't figure out why `Start-FalconSession` would not finish processing (which was ultimately why `Invoke-FalconRtr` was getting stuck). Given that it was solved with a different version of PowerShell, and no we could see no useful information about why the issue was occurring, I'm going to consider this solved with the use of a different PowerShell install/computer.
