### ISSUE TITLE
[ BUG ] Export-FalconReport does not export correct results from Get-FalconUser

### ISSUE THREAD

**Issue by NotJohnGrant** [CrowdStrike/psfalcon#187]
**Describe the bug**
Export-FalconReport is not correctly exporting user roles. Each user has one role exported even when assigned multiple roles. 
User with roles: {binarly_admin, custom_ioas_manager, dashboard_admin, device_control_manager, vulnerability_manager} will only have one role exported, vulnerability_manager. 

**To Reproduce**

`Get-FalconUser -Detailed -Include roles | Export-FalconReport test.csv`

**Expected behavior**
Export-FalconReport to export all roles assigned to a user.

**Environment (please complete the following information):**
 - OS: MacOS 12.2.1
 - PowerShell: 7.2.1  
 - PSFalcon: 2.1.7

**Comment by bk-cs** [comment]
Nice catch!

I believe this is due to a typo, and unfortunately affected every `[array]` value when using `Export-FalconReport`. The `Get-Array` function it uses was supposed to join all values in the array, but it was outputting a single result (the final one) instead. The corrected function will be included in the v2.1.8 release.

Please replace your `Public\psf-output.ps1` file with the content of this file to fix the problem until the release is available: https://raw.githubusercontent.com/CrowdStrike/psfalcon/master/Public/psf-output.ps1

**Comment by NotJohnGrant** [comment]
That did the trick, thanks for the assist!

**Comment by bk-cs** [comment]
Keeping issue open until v2.1.8 release in case other people want to resolve the same issue.

**Comment by bk-cs** [comment]
Fixed with v2.1.8 release which will be present on the PowerShell Gallery soon.
