### ISSUE TITLE
[ BUG ] codebase is invalid

### ISSUE THREAD

**Issue by etaylor77** [CrowdStrike/psfalcon#200]
**Describe the bug**
Import-Module gives error

**To Reproduce**
Import-Module -Name PSFalcon
Import-Module : The given assembly name or codebase was invalid. (Exception from HRESULT: 0x80131047)
At line:1 char:1

**Comment by bk-cs** [comment]
How did you install the module? If you didn't, can you remove your current module and follow the [PowerShell Gallery installation instructions](https://github.com/CrowdStrike/psfalcon/wiki/Installation,-Upgrade-and-Removal#use-the-powershell-gallery)?

**Comment by etaylor77** [comment]
I actually figured out that I needed PoSH v7+ to get this to run. Version 5 would just give me errors.

**Comment by bk-cs** [comment]
PSFalcon is compatible with both PowerShell Desktop (5.1) and PowerShell Core (6+). You should not be receiving an error like the one originally mentioned in this issue when using it within PowerShell 5.1.

I suspect there was some sort of problem during installation that caused the files to become corrupted which was not repeated when re-attempted with PowerShell Core. 

If you are OK using PowerShell Core, I recommend it because it is significantly faster than PowerShell Desktop. If you'd like to ensure that PSFalcon will work with PowerShell Desktop in your environment, please re-open this issue and let me know.
