### ISSUE TITLE
Write-Host During Import

### ISSUE THREAD

**Issue by zisk** [CrowdStrike/psfalcon#21]
It appears the library outputs the current version during import, which can lead to some issues if the output of a script needs to be parsed, which I am doing at the moment. Since the call is to `Write-Host` rather than `Write-Output` it is a little awkward to suppress since it can't be piped to `Out-Null`. Would it be possible to either remove this message or swap the call to something else?

https://github.com/CrowdStrike/psfalcon/blob/18ea92fa17c6c7dcba2f76aa9fdb17ffc15d15f8/PSFalcon.psm1#L38

**Comment by bk-cs** [comment]
Hi Zisk,

Thanks for posting this! May I ask what you mean by "parsing"? 

I added the "Write-Host" there because I envisioned it as an easy way to pinpoint issues that are caused by people using an improper module version. I chose Write-Host because I thought it would be the best way to display the ModuleVersion field without showing up in a script that's importing the modules, but it sounds like it's getting in your way anyway? I'm not aware of a better way to accomplish this, but appreciate feedback if you have any.

The only other time Write-Host is used is in "scripts" (Get-FalconQueue, Invoke-FalconDeploy, etc.). Do you think those will conflict with what you're trying to do?

**Comment by zisk** [comment]
Hello bk-cs,

We're using an RMM utility to create Host Groups for our child CIDs and link policies via script. In the end, the script engine system expects output in a specific format to parse into variables for storage (in this case `<Group1>=<GroupID>|<Group1>=GroupID>`. As it stands, I am getting the version output as soon as I import the module which muddles the parsing a bit.

I can silence it with the following so its not the end of the world, but it is an extra step.
```
Import-Module PSFalcon 6>$null
```

My understanding is that Write-Output is generally better practice since it can still be used in pipelines but I'm not sure that's exactly applicable in this case.

**Comment by bk-cs** [comment]
Thanks for the clarification! I removed the 'Write-Host' message and added a new command 'Show-FalconModule' which can be used to easily display some module and user-level information which will end up being more useful during troubleshooting. 

Please re-download and re-install the module and reply if you have any further issues.
