### ISSUE TITLE
Missing params on New-FalconIOC [eu-1]

### ISSUE THREAD

**Issue by AlvaroPlanet** [CrowdStrike/psfalcon#24]
There are no params "type" and "value" on cmdlet New-FalconIOC:

**New-FalconIOC -value testing.com -Description "Testing custom IOCs" -ShareLevel red -Source "Testing" -Policy none -ExpirationDays 2**

New-FalconIOC : No parameter is found matching the parameter name 'Type'.
On line: 1 Character: 15
+ New-FalconIOC -Type domain -value testing.com -Description "Testing c ...
    + CategoryInfo          : InvalidArgument: (:) [New-FalconIOC], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,New-FalconIOC

**New-FalconIOC -help**

#Create Custom IOCs
  Requires iocs:write

  -Policy [string]
    Action to perform when the Custom IOC is observed by a Host
      Enum : detect, none
      Position : 2

  -ShareLevel [string]
    Custom IOC visibility level
      Enum : red
      Position : 3

  -ExpirationDays [int32]
    Number of days before expiration (for 'domain' 'ipv4' and 'ipv6')
      Position : 4

  -Source [string]
    Custom IOC source
      Position : 5

  -Description [string]
    Custom IOC description
      Position : 6

**Comment by bk-cs** [comment]
Wow, not sure how I missed that one! Thanks for finding it. I just committed a change that re-added the type/value parameters and verified that I was able to successfully add an IOC.

Please note that you can only add one IOC at a time until I add a parameter that allows you to add many. And the API does not return any information when the IOC is created, but you can verify that the request happens if you use the -Verbose parameter (or check Get-FalconIOC to verify the IOC is there after).

**Comment by AlvaroPlanet** [comment]
> Wow, not sure how I missed that one! Thanks for finding it. I just committed a change that re-added the type/value parameters and verified that I was able to successfully add an IOC.
> 
> Please note that you can only add one IOC at a time until I add a parameter that allows you to add many. And the API does not return any information when the IOC is created, but you can verify that the request happens if you use the -Verbose parameter (or check Get-FalconIOC to verify the IOC is there after).

Thank you so much!!!
