### ISSUE TITLE
Get-FalconScore missing -All parameter

### ISSUE THREAD

**Issue by Factorization** [CrowdStrike/psfalcon#28]
The Wiki shows that `Get-FalconScore` has a `-All` parameter, but it looks like it is missing from the actual function. Is there an `-All` parameter for `Get-FalconScore`?

![image](https://user-images.githubusercontent.com/10674846/108576780-b37e5900-72d3-11eb-8001-a62a2ae4f16e.png)

![image](https://user-images.githubusercontent.com/10674846/108576787-bbd69400-72d3-11eb-9f8f-280cba449ce7.png)

**Comment by bk-cs** [comment]
Yes, there should be an `-All` parameter. I made some changes so that `-All` is added automatically, but it looks like that didn't include the CrowdScore values. Note that CrowdScore maxes out at 10,000 results, so when you use `-All` you'll see an error.

I'll add this change to the next version. I'm also adding some additional commands so it'll be a few days before it is available.

**Comment by Factorization** [comment]
Thanks! I ran into the 10,000 max when using the API directly with Python. That's what caused me to test with your PowerShell module to see if I could get more than 10,000.

**Comment by bk-cs** [comment]
Sadly, no... it is an API limitation imposed by the back-end system that's used to gather the scores.

I've made a change in v2.0.6 that correctly adds the `-All` parameter. Until release, you can fix it yourself by editing `Private\Private.ps1` and changing the following statement (line 441) in the `Get-Dictionary` function from...

`($Endpoints -match '/queries/').foreach{`

to...

`($Endpoints -match '(/combined/|/queries/)').foreach{`

**Comment by bk-cs** [comment]
Updated to v2.0.6.
