### ISSUE TITLE
[ BUG ] `Get-FalconCompleteCase` returning duplicates

### ISSUE THREAD

**Issue by SirSandmann** [CrowdStrike/psfalcon#304]
**Describe the bug**
`Get-FalconCompleteCase` with `-All` gives back the right total, but with a lot of duplicates if returning actual objects.

**To Reproduce**
For example running: 

`Get-FalconCompleteCase -Detailed -Filter "case.created_time:>='Last 30 days'" -Total
`
and then 

`Get-FalconCompleteCase -Detailed -Filter "case.created_time:>='Last 30 days'" -All | Sort-Object -Property id -Unique | Measure
`

Both commands are returning different results, as in the second command, several duplicates are included.

The same filter set in the Webinterface returns a different set of cases compared to the PsFalcon Get-FalconCompleteCase command.

**Expected behavior**
Receiving all entries without any duplicates when running Get-FalconCompleteCase.

**Environment (please complete the following information):**
 - OS:  Windows 10
 - PowerShell: 7.3.4
 - PSFalcon: 2.2.5

**Additional context**
-
 
**Transcript content**
-

**Comment by bk-cs** [comment]
Thank you for the report!

Unfortunately, I don't have access to an environment with any Falcon Complete case data. Would it be possible for you to either provide me with an API Client that has read only access (preferred option), or a verbose transcript?

```powershell
$VerbosePreference = 'Continue'
Request-FalconToken
Start-Transcript
Get-FalconCompleteCase -Detailed -Filter "case.created_time:>='Last 30 days'" -All
Stop-Transcript
```

I'm not aware of how the data works with that specific endpoint. It's possible that the cases themselves _are_ duplicated based on activity, and that's why the `id` values show up multiple times. Looking at the data should give me an indication.

**Comment by SirSandmann** [comment]
I intentionally didn´t send the transcript, because it contains a lot of internal information. For the same reason I won´t provide an API client. 

If I will find some time to dig into Powershell, I will have a look by myself!
