### ISSUE TITLE
Invoke-FalconRTR — runscript / 40014: Unrecognized flag found: Raw

### ISSUE THREAD

**Issue by datorr2** [CrowdStrike/psfalcon#33]
```powershell
Invoke-FalconRTR -Command 'runscript' -Arguments '-Raw=```Get-ChildItem -Path "C:\" ``` ' -HostId 'deadbeef'
```
Results in:
```powershell
Format-Result: C:\Program Files\WindowsPowerShell\Modules\PSFalcon\Private\Private.ps1:995
Line |
 995 |                  Format-Result -Response $Response -Endpoint $Endpoint
     |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | 40014: Unrecognized flag found: Raw, value: Get-ChildItem -Path "C:\"
 ```

Note: I understand that I can use the 'ls' command instead, but I was testing the -Raw flag before I tried to use a different command/set of commands.

**Comment by bk-cs** [comment]
I think the escape characters are getting lost in translation. PSFalcon has to convert the `-Arguments` string into Json, then the API converts it back to text, then it gets pushed to the host for execution. In this case, the RTR API is returning that result. 

I generally don't recommend using the `-Raw=` capability with PSFalcon because of these potential translation issues. If you create a script first, and upload it to Response Scripts and Files (via the UI or `Send-FalconScript`, though you'll want to keep [Issue #31](https://github.com/CrowdStrike/psfalcon/issues/31) in mind) you can execute it using `-CloudFile='ScriptName'` , or you can encode the `-Raw=` content using PowerShell and have a wrapper script that decodes and executes which lives in your script library, or pass that as the `-Raw=` content.

I've been considering ways to improve `Invoke-FalconRTR` specifically for this purpose, or potentially create a separate "RTR Tools" type module for those users that really just want to run RTR commands. Unfortunately I haven't had the time to do it yet. 

I'll add this as a project item to see what I can figure out in the future, but for now, I recommend either trying to save the `-Raw` content to a pre-existing variable and then passing it (to see if that fixes the formatting) or exploring the encoded command possibility. Sorry for not having an easy fix on this one... I've struggled with it myself at various times.

**Comment by bk-cs** [comment]
Realizing it's not necessarily an elegant solution, here's one way you could do it...

1. Create a [Custom Script](https://falcon.crowdstrike.com/configuration/real-time-response/tools/scripts) named `RunEncoded` with the following content:
```
param(
    [Parameter(Mandatory=$true,
        Position=1)]
    [string] $Encoded
)
powershell.exe -Encoded $Encoded
```

2. Encode your command
```
function ToBase64 ($String) {
    [System.Convert]::ToBase64String([System.Text.Encoding]::UNICODE.GetBytes($String))
}
$Command = ToBase64 "Get-ChildItem -Path C:\"
```

3. Use `Invoke-FalconRTR` to run the script
```
Invoke-FalconRTR runscript "-CloudFile='RunEncoded' -CommandLine='$Command'" -HostId 'deadbeef'
```

**Comment by bk-cs** [comment]
I did some further testing and found out this is a bug. `Invoke-FalconRTR` defaults to using Active Responder permissions, which is not allowed to use the `-Raw` parameter. I'll make a change to update the command in the next version.
