### ISSUE TITLE
[ BUG ] `Get-FalconRole` does not display custom roles

### ISSUE THREAD

**Issue by plus-zz** [CrowdStrike/psfalcon#374]
**Describe the bug**
get-FalconRole gives error messages for every custom role

**To Reproduce**
Get parent API-Key. 
Create Child CID Custom role.
Use get-FalconRole -CID xxxx to query all roles.
Get first error messages for every custom role, then all default roles displayed.

**Environment (please complete the following information):**
 - PSFalcon: 2.2.5

**Comment by plus-zz** [comment]
Updated to PSFalcon 2.2.6 - Now no error messages anymore. But IDs of custom roles will not be displayed.

PS: I love this PowerShell PSFalcon module, the wiki and the easy way of administration. Thank you for your awesome module, making everyday easier!

**Comment by bk-cs** [comment]
In my testing, the following command _does_ return the role information for custom roles (i.e. those with an identifier value rather than plain text role label):
```
Get-FalconRole -Cid xxx | Get-FalconRole
```
The problem is that custom roles return a `cid` value while the standard roles *do not*.  Because of how PowerShell works, that means that you don't see the custom role in the final output. You can use `Format-List` to see that it is there:
```powershell
Get-FalconRole -Cid xxx | Get-FalconRole | Format-List
```
Or, you can use `Select-Object` to force it to show in the table (with `cid` being empty for all the other roles):
```
Get-FalconRole -Cid xxx | Get-FalconRole | Select-Object id,display_name,description,is_global,cid
```

**Comment by plus-zz** [comment]
Thank you for your code-snippets.
It's working like you described.

Maybe you can help me with a problem I try to solve.

I want in the end to create some kind of excel pivot table.
Rows = Settings enabled / disabled within a Role.
Columns = RoleName

Why this?
CustomRoles will have the name of an EntraAD Security Group.
Automation will add analysts to the corresponding Roles. (We have ~200 Analysts in total)
Role permissions can be negotiated between different teams and then assigned. 

Questions:
How can I get a csv export of all enabled security settings for Custom Groups per CID?

Thank you for your super fast response! 🥇 
Patrick

**Comment by bk-cs** [comment]
> How can I get a csv export of all enabled security settings for custom groups per CID?

There isn't an API available that will output the permissions for a given role. :(
