### ISSUE TITLE
[ ENHANCEMENT ] Add command to overwrite SensorTags instead of appending

### ISSUE THREAD

**Issue by LyleWB** [CrowdStrike/psfalcon#389]
Hi, I wasn't sure if this was the correct place to post this as it's more of a feature request than a bug - apologies in advance if this should be posted elsewhere.

**Describe the bug**
This is a feature request for an "Append" switch to be added to Add-FalconSensorTag. Currently, this command will take the existing tags and add additional tags; retaining the pre-existing ones. I would like a switch to enable/disable retaining the pre-existing tags. 

**To Reproduce**
Below is a function I created to replace a sensor grouping tag using the "Remove-FalconSensorTag" & "Add-FalconSensorTag" commands. If you run this function, you will notice that the 2nd RTR script is re-adding the previous tags, because the initial RTR script has not finished running. 

```powershell
function Replace-SensorTags {
    [CmdletBinding()]
    param (
        [Parameter(Mandatory)]
        [string[]]$Before,
        [string[]]$After
    )
	Write-Host "`nRetrieving Hosts"
	$Hosts = @(Get-FalconHost -Detailed -Limit 5000)
	Write-Host Total of $Hosts.count Devices

	foreach($ID in $Hosts) {
		Write-Host Removing $Before tag from $ID.hostname
		Remove-FalconSensorTag -Id $ID.device_id -Tag $Before -QueueOffline $true | Out-Null
		Write-Host Adding $After tag from $ID.hostname `n
		Add-FalconSensorTag -Id $ID.device_id -Tag $After -QueueOffline $true | Out-Null
	}
}
``` 

**Expected behavior**
Effectively, I would like the below behaviour, with the default value of $true.

If the -append switch is true - previous tags + new tag.
if the -append switch is false - new tag only.

**Environment (please complete the following information):**
 - OS: Windows 10, Windows 11
 - PowerShell: 5.1.22621.2506
 - PSFalcon: 2.2.5

**Additional context**
We have Flight Control and tag devices within a CID with the services we offer. This allows our analysts to see services offered to each CID. It also allows us to assign Fusion workflows to all CID's and filter by sensor tag (you can't assign workflows to CID groups).

We want to use Sensor tags over Grouping tags so that this can be added to deployment jobs and future devices are automatically tagged. 

**Transcript content**
Not possible.

**Comment by bk-cs** [comment]
I'm not sure that `Add-FalconSensorTag` is [functioning properly](https://github.com/CrowdStrike/psfalcon/issues/385) at the moment. Otherwise, I expect that your script would do what you are trying to do.

I'd rather not change the command by adding the `Append` parameter, as my assumption would be that it would not be `$true` by default (leading to a change in the default behavior of the command, as boolean parameters are `$false` unless set by the user).

What about a `Set-FalconSensorTag` command? `CsSensorSettings.exe` (used to set the tags) does not ever append tags -- it only writes over the existing tags with whatever value you provide. PSFalcon adds the "keep what's there" behavior. Adding a new command would ensure no existing users are impacted but still lead to your desired outcome.

**Comment by LyleWB** [comment]
I think that would be a good workaround! This issue is similar to the one outlined in the other thread, but it doesn't seem to be an issue with the maintenance token, the tags just aren't passed properly to the "$V" variable in the RTR script. Might be related, might not be.

**Comment by bk-cs** [comment]
I added the `Set-FalconSensorTag` command which will be available in the next release. I'll leave this open until the next release is available.

Thanks for the idea!

**Comment by bk-cs** [comment]
The [2.2.7 release](https://github.com/CrowdStrike/psfalcon/releases/tag/2.2.7) is now available.
