### ISSUE TITLE
Invoke-FalconRTR

### ISSUE THREAD

**Issue by Ainsley929** [CrowdStrike/psfalcon#80]
We are getting a 404 failure to initiate rtr session when trying to run a cloud file. -QueueOffline $true is not working for some reason

**Comment by bk-cs** [comment]
- Are you getting an HTTP 404 error, or `404: no successful hosts initialized on RTR`? 

- What are your API client permissions? For `Invoke-FalconRtr`, you should have all three as the requirements change depending on the issued command:

`real-time-response:read`
`real-time-response:write`
`real-time-response-admin:write`

- What cloud are you in?
- Can you provide a transcript?

```
Import-Module PSFalcon
Request-FalconToken <...>
$VerbosePreference = 'Continue'
Start-Transcript
Invoke-FalconRtr <...>
Stop-Transcript
$VerbosePreference = 'SilentlyContinue'
```

**Comment by Ainsley929** [comment]
404: no successful hosts initialized on RTR is what we are getting
confirmed API has all correct permissions
Cloud= Complete

**Comment by bk-cs** [comment]
Can you provide a transcript or exact syntax for how you're sending the command? I'm able to `-QueueOffline $true` without issue, so I'm going to have to see what happens as the module is being used.

**Comment by Ainsley929** [comment]
Invoke-FalconRTR -Command runscript -Arguments "-CloudFile='file.ps1'" -HostIds $variable -QueueOffline $true

result = write-result : 404 no successful hosts initialized on RTR

I've used this same exact command in another console, not Complete, and it worked perfectly. I don't understand the difference.

**Comment by bk-cs** [comment]
I assume when you say that it works from the console, you don't mean `-QueueOffline`? That will not work from the console. 

The error that you're getting is due to the API saying that it can't contact any of the hosts in `$variable`. It has nothing to do with PSFalcon--unless the reason that it's happening is because the `-QueueOffline` parameter is not being properly applied at the beginning of the session. I can't tell if that's the case without the transcript. 

Most often when people report issues, it's due to the module being installed improperly. If the module isn't in either your "all users" or specific user module folder, it can cause sporadic issues. You can `Uninstall-Module PSFalcon -AllVersions` and then `Install-Module PSFalcon -Scope CurrentUser` to force a proper install with the latest version and see if that resolves it.

Either way, I'll need a transcript with included `trace_id` values (captured in the verbose output) if I'm going to try and troubleshoot this for you.

**Comment by Ainsley929** [comment]
Appreciate the quick responses and support! You've given me a couple things to try for the moment.

When I said console I meant another Falcon instance, not direct from the console. Apologies for the confusion. I'll loop back with a transcript if not resolved.

**Comment by Ainsley929** [comment]
hey so my apologies for wasting your time. I honestly don't know what the issue was but it is working fine now... I was going to uninstall and re-install but thought I'd try again before and it works. so yeah, I'll close this down and go crawl into a hole somewhere. 

Thanks, PSFalcon is a life saver!

**Comment by bk-cs** [comment]
No problem--every once and awhile I do the same thing. Think something's broken and don't realize I'm pointing to the wrong ID, the device is powered off, etc.

My guess? The devices recently went offline and the "offline_queue" was treating them as "online" and thus it was failing.

Falcon communication is sensor initiated, so when a device is powered off, the cloud doesn't know it for about 10-15 minutes. In that time, if you try and start a Real-time Response session, the API will attempt to connect and fail (because the cloud thinks the device is online, and thus isn't queueing the session).

**Comment by Ainsley929** [comment]
really good to know! I hadn't considered how much delay there. We were testing against recently powered down hosts. I think you just solved it
